const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage({ baseURL: 'http://127.0.0.1:5173' });
  page.on('console', msg => console.log('console', msg.type(), msg.text()));
  page.on('pageerror', err => console.log('pageerror', err.message));
  await page.route('http://127.0.0.1:8000/bajadas-v2/cotizar', async route => route.fulfill({status:200, contentType:'application/json', body: JSON.stringify({precio_unitario_sin_iva:437.93, precio_unitario_con_urgencia:437.93, precio_unitario_base_sin_iva:437.93, cantidad_unidades:1, cantidad_rango_aplicado:'1', total_sin_iva:437.93, total_con_urgencia:437.93, precio_sin_iva:437.93, precio_con_recargo_urgencia:437.93, adicional_laminado:'sin_adicional', regla_aplicada:'TEST_A4_115G', fuente:'mock_pdf', trazabilidad:{recargo_urgencia_aplicado:0}})}));
  await page.route('**/variables-impacto', async route => route.fulfill({status:200, contentType:'application/json', body: JSON.stringify({ok:true, variables:[], productos:[], relaciones:[], resumen:{}})}));
  await page.route('**/admin-precios/variables-editables', async route => route.fulfill({status:200, contentType:'application/json', body: JSON.stringify({ok:true, variables:[]})}));
  await page.goto('/', { waitUntil: 'domcontentloaded' });
  await page.getByLabel('Medida / formato').selectOption('A4');
  await page.getByLabel('Tipo de papel').selectOption('liviano');
  await page.getByLabel('Material').selectOption('Ilustracion');
  await page.getByLabel('Gramaje').selectOption('115g');
  await page.getByLabel('Cantidad').fill('1');
  await page.getByRole('button', { name: 'Calcular' }).click();
  await page.getByText('Total final con urgencia').waitFor();
  await page.getByTestId('tab-understand-price').click();
  await page.getByTestId('view-mode-advanced').click();
  console.log('before trace button visible', await page.getByTestId('understand-trace-button').isVisible());
  await page.getByTestId('understand-trace-button').click();
  await page.waitForTimeout(1000);
  console.log('trace mode count', await page.getByTestId('trace-mode-cotizacion_actual').count());
  console.log((await page.locator('body').innerText()).slice(0, 2000));
  await browser.close();
})().catch(err => { console.error(err); process.exit(1); });