flowchart TD
  A["Bajadas"]
  P["PAPEL US$"]
  F1["A3 PLUS pack color"]
  A --> F1
  F2["A3+"]
  A --> F2
  F3["A4 ByN"]
  A --> F3
  F4["A4 color"]
  A --> F4
  F5["XA3"]
  A --> F5
  F6["XA3 ByN"]
  A --> F6
  F7["XL 32x70"]
  A --> F7
  F8["XL ByN"]
  A --> F8
  O1["SB02 C4"]
  F2 --> O1
  O1 --> P
  O2["SB02 D4"]
  F2 --> O2
  O2 --> P
  O3["SB02 E4"]
  F2 --> O3
  O3 --> P
  O4["SB02 F4"]
  F2 --> O4
  O4 --> P
  O5["SB02 G4"]
  F2 --> O5
  O5 --> P
  O6["SB02 H4"]
  F2 --> O6
  O6 --> P
  O7["SB02 I4"]
  F2 --> O7
  O7 --> P
  O8["SB02 J4"]
  F2 --> O8
  O8 --> P
  O9["SB02 K4"]
  F2 --> O9
  O9 --> P
  O10["SB02 L4"]
  F2 --> O10
  O10 --> P
  O11["SB02 M4"]
  F2 --> O11
  O11 --> P
  O12["SB02 N4"]
  F2 --> O12
  O12 --> P
  O13["SB02 O4"]
  F2 --> O13
  O13 --> P
  O14["SB02 P4"]
  F2 --> O14
  O14 --> P
  O15["SB02 Q4"]
  F2 --> O15
  O15 --> P
  O16["SB02 R4"]
  F2 --> O16
  O16 --> P
  O17["SB02 S4"]
  F2 --> O17
  O17 --> P
  O18["SB02 T4"]
  F2 --> O18
  O18 --> P
  O19["SB02 U4"]
  F2 --> O19
  O19 --> P
  O20["SB02 C5"]
  F2 --> O20
  O20 --> P
  O21["SB02 D5"]
  F2 --> O21
  O21 --> P
  O22["SB02 E5"]
  F2 --> O22
  O22 --> P
  O23["SB02 F5"]
  F2 --> O23
  O23 --> P
  O24["SB02 G5"]
  F2 --> O24
  O24 --> P
  O25["SB02 H5"]
  F2 --> O25
  O25 --> P
  O26["SB02 I5"]
  F2 --> O26
  O26 --> P
  O27["SB02 J5"]
  F2 --> O27
  O27 --> P
  O28["SB02 K5"]
  F2 --> O28
  O28 --> P
  O29["SB02 L5"]
  F2 --> O29
  O29 --> P
  O30["SB02 M5"]
  F2 --> O30
  O30 --> P
  O31["SB02 N5"]
  F2 --> O31
  O31 --> P
  O32["SB02 O5"]
  F2 --> O32
  O32 --> P
  O33["SB02 P5"]
  F2 --> O33
  O33 --> P
  O34["SB02 Q5"]
  F2 --> O34
  O34 --> P
  O35["SB02 R5"]
  F2 --> O35
  O35 --> P
  O36["SB02 S5"]
  F2 --> O36
  O36 --> P